modLoader="javafml" #mandatory
loaderVersion="[35,)"
license="GNU General Public License"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="fansmod" #mandatory
version="2.0.1.1" #mandatory
displayName="Fans Mod" #mandatory
logoFile="logo_scaled.png" #optional
displayURL="https://przemyk.xyz/mods/fansmod/index.html" #optional
description='''
This mod adds fans.
'''
[[dependencies.fansmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.fansmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
